#!/usr/bin/env node
// One command to turn a language's authored source into everything else:
//
//   node app/scripts/lang/build.mjs <code> [--draft] [--offline]
//
//   1. validate.mjs         stops here on errors, unless --draft
//   2. build-strokes.mjs    app/src/lang/<code>/strokes.generated.ts + out/<code>-strokes.html
//   3. build-flashcards.mjs public/art/flashcards/<code>/ + cards.generated.ts + out/<code>-art-manifest.json
//   4. pack.generated.ts    the pack as a typed module (checked by `npx tsc -b`)
//   5. preview.mjs          out/<code>-review.html (the native-speaker review sheet)
//
// Audio is separate (paid API, slow): node assets/generate-language-audio.mjs --lang=<code>

import { spawnSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ensureDir, generatedDir, loadPack, parseArgs, sourceDir } from './lib.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const { flags, positional } = parseArgs();
const code = positional[0];
if (!code) {
  console.error('Usage: node app/scripts/lang/build.mjs <code> [--draft] [--offline]');
  process.exit(2);
}

function step(label, script, args) {
  console.log(`\n── ${label}`);
  const res = spawnSync(process.execPath, [join(HERE, script), ...args], { stdio: 'inherit' });
  return res.status === 0;
}

const valid = step('validate', 'validate.mjs', [code, ...(flags.offline ? ['--offline'] : [])]);
if (!valid && !flags.draft) {
  console.error(`\nValidation failed — fix the errors above, or pass --draft to build previews anyway.`);
  process.exit(1);
}

if (existsSync(join(sourceDir(code), 'strokes.mjs'))) step('strokes', 'build-strokes.mjs', [code, '--preview']);
step('flash cards', 'build-flashcards.mjs', [code, '--art-manifest']);

console.log('\n── pack module');
const pack = loadPack(code);
ensureDir(generatedDir(code));
const out = join(generatedDir(code), 'pack.generated.ts');
writeFileSync(
  out,
  `// GENERATED by app/scripts/lang/build.mjs from app/languages/${code}/pack.json — do not edit.
// Typed against the contract, so \`npx tsc -b\` catches any shape drift.
import type { LanguagePack } from '../types';

export const PACK: LanguagePack = ${JSON.stringify(pack, null, 2)};
`,
);
console.log(`Wrote ${out}`);

step('review sheet', 'preview.mjs', [code]);

console.log(`\nDone${valid ? '' : ' (DRAFT — validation errors remain)'}. Next: \`cd app && npx tsc -b\`, open the previews in app/scripts/lang/out/, then generate audio.`);
