#!/usr/bin/env node
// Builds a language's stroke-order data and (optionally) a visual preview.
//
//   node app/scripts/lang/build-strokes.mjs <code> [--preview]
//
// Reads app/languages/<code>/strokes.mjs, checks every path, and writes
// app/src/lang/<code>/strokes.generated.ts. With --preview, also writes
// app/scripts/lang/out/<code>-strokes.html: every form with its guide lines,
// numbered strokes, start dots and direction arrows, laid over the display
// font's glyph fitted exactly the way three/strokeFit.ts fits the tracing
// guide onto the letter cloud — so what you see is what the child traces.
// Open it in a browser (or screenshot it headlessly) and check every letter.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { ensureDir, escapeHtml, generatedDir, googleFontsCssHref, loadPack, loadTs, OUT_DIR, parseArgs, sourceDir } from './lib.mjs';
import { createStrokeKit, GUIDE_METRICS } from './stroke-kit.mjs';

const { flags, positional } = parseArgs();
const code = positional[0];
if (!code) {
  console.error('Usage: node app/scripts/lang/build-strokes.mjs <code> [--preview]');
  process.exit(2);
}

const pack = loadPack(code);
const guide = pack.script.writingGuide;
const metrics = GUIDE_METRICS[guide];
const mod = await import(pathToFileURL(join(sourceDir(code), 'strokes.mjs')).href);
const forms = await mod.default(createStrokeKit(guide), { loadTs });

// --- checks --------------------------------------------------------------
const problems = [];
const [vx, vy, vw, vh] = metrics.viewBox;
const MARGIN = 4;
for (const [ch, strokes] of Object.entries(forms)) {
  if (!Array.isArray(strokes)) {
    problems.push(`"${ch}": not an array`);
    continue;
  }
  strokes.forEach((d, i) => {
    if (typeof d !== 'string' || !/^\s*M/.test(d)) return problems.push(`"${ch}" stroke ${i + 1}: must be a path string starting with M`);
    const bad = d.replace(/[MLQCAZmlqcaz]|-?\d*\.?\d+(e-?\d+)?|[\s,]/g, '');
    if (bad) problems.push(`"${ch}" stroke ${i + 1}: unexpected "${bad}" (only M L Q C A Z)`);
    if (/[mlqcaz]/.test(d)) problems.push(`"${ch}" stroke ${i + 1}: use absolute commands only`);
    if (/M/.test(d.slice(1))) problems.push(`"${ch}" stroke ${i + 1}: a second M is a pen lift — split it into its own stroke`);
    // Endpoint coordinates (every x,y pair; arc radii are "rx,ry" too but stay small, so bounds still hold).
    for (const m of d.matchAll(/(-?\d*\.?\d+),(-?\d*\.?\d+)/g)) {
      const x = Number(m[1]);
      const y = Number(m[2]);
      if (x < vx - MARGIN || x > vx + vw + MARGIN || y < vy - MARGIN || y > vy + vh + MARGIN) problems.push(`"${ch}" stroke ${i + 1}: point ${x},${y} outside the ${guide} viewBox`);
    }
  });
}
const expected = pack.letters.flatMap((l) => [l.char, l.secondary].filter(Boolean));
const missing = expected.filter((ch) => !forms[ch]?.length);

// --- generated module ----------------------------------------------------
const out = join(generatedDir(code), 'strokes.generated.ts');
ensureDir(generatedDir(code));
writeFileSync(
  out,
  `// GENERATED by app/scripts/lang/build-strokes.mjs from app/languages/${code}/strokes.mjs — do not edit.
// One SVG path per pen stroke, in teaching order; see app/scripts/lang/stroke-kit.mjs.

export const STROKE_GUIDE = ${JSON.stringify(guide)} as const;
export const STROKE_VIEW_BOX = ${JSON.stringify(metrics.viewBox.join(' '))};
export const STROKE_LINES = ${JSON.stringify(metrics.lines)} as const;

export const STROKES: Record<string, readonly string[]> = ${JSON.stringify(forms, null, 2)};
`,
);
console.log(`Wrote ${out} (${Object.keys(forms).length} forms).`);

// --- preview ---------------------------------------------------------------
if (flags.preview) {
  const font = pack.script.fonts.display;
  const lineMarkup = Object.entries(metrics.lines)
    .map(([name, v]) =>
      ['left', 'right'].includes(name)
        ? `<line x1="${v}" y1="${vy}" x2="${v}" y2="${vy + vh}" class="gl"/>`
        : `<line x1="${vx}" y1="${v}" x2="${vx + vw}" y2="${v}" class="gl ${name === 'base' ? 'base' : ''}"/>`,
    )
    .join('') + (guide === 'grid' ? `<line x1="50" y1="${vy}" x2="50" y2="${vy + vh}" class="gl"/>` : '');
  const cells = expected
    .map((ch) => {
      const strokes = forms[ch] ?? [];
      const paths = strokes
        .map((d, i) => `<path d="${d}" class="s" style="--h:${(i * 67) % 360}" marker-end="url(#arrow)"/><text class="n" data-stroke="${i}">${i + 1}</text>`)
        .join('');
      const owner = pack.letters.find((l) => l.char === ch || l.secondary === ch);
      return `<figure class="cell${strokes.length ? '' : ' missing'}" data-char="${escapeHtml(ch)}">
  <svg viewBox="${metrics.viewBox.join(' ')}">${lineMarkup}<g class="strokes">${paths}</g></svg>
  <figcaption><b dir="${pack.script.direction}">${escapeHtml(ch.replace(/‍/g, ''))}</b> ${escapeHtml(owner?.id ?? '')} · ${strokes.length || 'NO'} stroke${strokes.length === 1 ? '' : 's'}</figcaption>
</figure>`;
    })
    .join('\n');

  const html = `<!doctype html>
<html lang="${code}"><head><meta charset="utf-8"><title>${escapeHtml(pack.name)} strokes</title>
<link rel="stylesheet" href="${googleFontsCssHref([font])}">
<style>
  body { font: 14px system-ui, sans-serif; margin: 16px; background: #fbf8f2; color: #332d29; }
  h1 { font-size: 18px; margin: 0 0 4px; } p { margin: 0 0 12px; color: #6b5f55; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 10px; }
  .cell { margin: 0; background: #fff; border: 1px solid #e3d8c8; border-radius: 10px; padding: 6px; }
  .cell.missing { border-color: #e26a57; background: #fff1ee; }
  .cell svg { width: 100%; display: block; }
  .gl { stroke: #9cc3d9; stroke-width: 0.5; stroke-dasharray: 2 2; } .gl.base { stroke: #5a9bc0; stroke-dasharray: none; }
  .s { fill: none; stroke: hsl(var(--h) 70% 45%); stroke-width: 2.4; stroke-linecap: round; stroke-linejoin: round; }
  .n { font: 700 7px system-ui; fill: #fff; paint-order: stroke; stroke: #332d29; stroke-width: 1.6px; }
  .dot { fill: #332d29; }
  figcaption { font-size: 12px; margin-top: 4px; } figcaption b { font-size: 16px; }
  image { opacity: 0.22; }
</style></head><body>
<h1>${escapeHtml(pack.name)} (${code}) — stroke order, guide "${guide}"</h1>
<p>Grey glyph: the cloud font (${escapeHtml(font.family)} ${font.weight}) fitted onto the strokes the way three/strokeFit.ts does it. Numbers and dots mark where each stroke starts; arrows show direction. Red cells have no strokes yet.</p>
<svg width="0" height="0" style="position:absolute"><defs><marker id="arrow" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#332d29"/></marker></defs></svg>
<div class="grid">
${cells}
</div>
<script>
// Mirror of three/strokeFit.ts: sample the glyph at 240px, take its ink
// bounding box inset by half a stem, and map it onto the strokes' bbox.
const FONT = ${JSON.stringify(`${font.weight} 240px "${font.family}"`)};
const INSET_X = 20, INSET_Y = 18;
function glyphBox(ch) {
  const size = Math.round(240 * 1.3);
  const c = document.createElement('canvas'); c.width = c.height = size;
  const ctx = c.getContext('2d');
  ctx.font = FONT; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillStyle = '#000';
  ctx.fillText(ch, size / 2, size / 2 + 240 * 0.05);
  const d = ctx.getImageData(0, 0, size, size).data;
  let x0 = size, x1 = 0, y0 = size, y1 = 0;
  for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) if (d[(x + y * size) * 4 + 3] > 80) { if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; }
  return x1 < x0 ? null : { canvas: c, x0, x1, y0, y1, size };
}
document.fonts.load(FONT).then(() => {
  for (const cell of document.querySelectorAll('.cell')) {
    const svg = cell.querySelector('svg');
    const g = cell.querySelector('.strokes');
    for (const path of g.querySelectorAll('path')) {
      const p = path.getPointAtLength(0);
      const n = path.nextElementSibling; n.setAttribute('x', p.x + 1.5); n.setAttribute('y', p.y - 1.5);
      const dot = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
      dot.setAttribute('cx', p.x); dot.setAttribute('cy', p.y); dot.setAttribute('r', 1.6); dot.setAttribute('class', 'dot');
      g.appendChild(dot);
    }
    if (!g.querySelector('path')) continue;
    const sb = g.getBBox();
    const gb = glyphBox(cell.dataset.char);
    if (!gb) continue;
    // Inset glyph box (the centreline skeleton) -> stroke box; then place the whole canvas accordingly.
    const gx0 = gb.x0 + INSET_X, gx1 = gb.x1 - INSET_X, gy0 = gb.y0 + INSET_Y, gy1 = gb.y1 - INSET_Y;
    const narrow = gx1 - gx0 < 8 || sb.width < 8;
    const sx = narrow ? sb.height / Math.max(1, gy1 - gy0) : sb.width / Math.max(1, gx1 - gx0);
    const sy = sb.height / Math.max(1, gy1 - gy0);
    const img = document.createElementNS('http://www.w3.org/2000/svg', 'image');
    img.setAttribute('href', gb.canvas.toDataURL());
    img.setAttribute('preserveAspectRatio', 'none');
    const cx = narrow ? sb.x + sb.width / 2 - ((gb.x0 + gb.x1) / 2) * sx : sb.x - gx0 * sx;
    img.setAttribute('x', cx); img.setAttribute('y', sb.y - gy0 * sy);
    img.setAttribute('width', gb.size * sx); img.setAttribute('height', gb.size * sy);
    svg.insertBefore(img, svg.firstChild);
  }
  document.body.dataset.ready = '1';
});
</script>
</body></html>
`;
  ensureDir(OUT_DIR);
  const previewPath = join(OUT_DIR, `${code}-strokes.html`);
  writeFileSync(previewPath, html);
  console.log(`Preview: ${previewPath}`);
}

if (missing.length) console.log(`\n${missing.length} form(s) have no strokes yet: ${missing.join(' ')}`);
if (problems.length) {
  console.error(`\n${problems.length} problem(s):\n  ✗ ${problems.join('\n  ✗ ')}`);
  process.exit(1);
}
